In [1]:
# step-1 we have tnote bookimport the dataset to the colab
import pandas as pd
df=pd.read_csv('Data.csv')

In [2]:
type(df)

pandas.core.frame.DataFrame

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
# grouping the input colums and output colums
X=df.iloc[:,0:3]

In [5]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [6]:
Y=df.iloc[:,-1]

In [7]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [8]:
X=X.values

In [9]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
Y=Y.values

In [11]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [12]:
 #step-3 handling missing data or values
 #scenario-1:missing values in numerical coloumn
 #scenario-2:missing values in non-numerical coloumn
 #scenario-3:missing values in huge data set



In [13]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [14]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [15]:
# step-4 handling the cetogorical data
#which converts the text data into numeric data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Alexa-0,0,1

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
np.remainder='passthrough'
X=ct.fit_transform(X)


In [16]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [18]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [19]:
# step-5: split the data into traing and testing and testing data
# train test split is class which is used to import from sk.model selection
#it was used to spliting the data into traing and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [20]:
X_train,X_test

(array([[0.0, 0.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 0.0, 37.0, 67000.0],
        [1.0, 0.0, 0.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 48.0, 79000.0],
        [0.0, 0.0, 1.0, 27.0, 48000.0],
        [0.0, 1.0, 0.0, 50.0, 83000.0],
        [1.0, 0.0, 0.0, 35.0, 58000.0],
        [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object),
 array([[0.0, 1.0, 0.0, 30.0, 54000.0],
        [0.0, 0.0, 1.0, 38.77777777777778, 52000.0]], dtype=object))

In [21]:
Y_train,Y_test

(array([0, 1, 0, 1, 1, 0, 1, 1]), array([0, 0]))

In [22]:
# step-6  features scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])

X_test[:,3:]=sc.transform(X_test[:,3:])

In [23]:
X_train,X_test

(array([[0.0, 0.0, 1.0, -0.2696254806921058, -0.5127583594408928],
        [1.0, 0.0, 0.0, -0.41342573706122887, 0.049453851925771716],
        [1.0, 0.0, 0.0, 0.5931760575226327, 0.5179640280646588],
        [1.0, 0.0, 0.0, 1.1683770829991251, 1.1738782746591006],
        [0.0, 0.0, 1.0, -1.8514283007524597, -1.730884817401999],
        [0.0, 1.0, 0.0, 1.4559775957373713, 1.5486864155702103],
        [1.0, 0.0, 0.0, -0.701026249799475, -0.7938644651242249],
        [0.0, 1.0, 0.0, 0.017975032046140385, -0.25247492825262186]],
       dtype=object),
 array([[0.0, 1.0, 0.0, -1.4200275316450905, -1.1686726060353345],
        [0.0, 0.0, 1.0, -0.15778083684945438, -1.3560766764908894]],
       dtype=object))

# New Section

In [24]:
# machine learning --we have to able to gather data , process data, and training the model .
# types in machine learning:---they are categorized based on data and dataset
#1--supervised machine learning                #(when we have to labled the data,and model tasks are classification and prediction)
# two algorithms   -(logistic regression ,linear regression)
#2--unsupervised machine learning              #(unlabled data,model remembers[algorithms-] or performs the patterns and we can perform predictions also)
#3--reinforcement machine learning             #(trail and error method,model will learn from failures)

In [25]:
# logistic regression algorithim(when the model perform classificathon task we have to logistic regression algorithm)
#linear regression(when model perform prediction task we have to apply this)

In [28]:
#step-7
# applying algorithim to traing data for model training
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)


LogisticRegression()

In [30]:
Y_pred=classifier.predict(X_test)

In [31]:
Y_pred

array([1, 1])